language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.2"
script: "npm run-script test"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
